local L = LibStub("AceLocale-3.0"):NewLocale("WowVision", "deDE")
if not L then return end

L["Chat"] = "Chat"
L["Message Alert"] = "Nachrichtenalarm"

-- Chat line parts (the clickable pieces of a message)
L["Previous Link in Message"] = "Vorheriger Link in der Nachricht"
L["Next Link in Message"] = "Nächster Link in der Nachricht"
L["Shift Click"] = "Umschaltklick"
L["Copy Line"] = "Zeile kopieren"
L["Copy now"] = "Jetzt kopieren"
L["Chat Box Opened"] = "Chat-Eingabefeld geöffnet"
L["Chat Box Closed"] = "Chat-Eingabefeld geschlossen"
L["Links unavailable here"] = "Links hier nicht verfügbar"
L["Player"] = "Spieler"
L["Channel"] = "Kanal"
L["Link"] = "Link"
L["Item"] = "Gegenstand"
L["Quest"] = "Quest"
L["Spell"] = "Zauber"
L["Talent"] = "Talent"
L["Achievement"] = "Erfolg"
L["Profession"] = "Beruf"
L["Currency"] = "Währung"
L["Whisper %s"] = "%s anflüstern"
L["Player Menu for %s"] = "Spielermenü für %s"
L["Who %s"] = "Wer-Abfrage für %s"
L["Write to %s"] = "In %s schreiben"
L["Channel Menu for %s"] = "Kanalmenü für %s"
L["Read Tooltip of %s"] = "Tooltip von %s vorlesen"
L["Link %s in Chat"] = "%s im Chat verlinken"
